version: '3.9'

services:
    
  mqttbroker:
    container_name: mosquitto_mqtt
    image: eclipse-mosquitto:latest
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/mosquitto/data"
      - "/mosquitto/log"
    ports:
      - "1883:1883"
      - "9001:9001"

