version: '3.2'


services:

  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
      - redis-config:/usr/local/etc/redis


volumes:
  redis-data:
  redis-config:
